spring:
  application:
    name: SamrtFactory
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_factory?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xiaomei.entity